# Generated by Django 3.0.14 on 2021-06-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_auto_20210531_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(to='baseApp.Tag'),
        ),
    ]
